# typed: true
# frozen_string_literal: true

require "English"
require "active_support"
require "active_support/cache"
require "active_support/core_ext/hash/indifferent_access"
require "active_support/core_ext/module/delegation"
require "active_support/core_ext/string"
require "active_support/core_ext/string/inflections"
require "active_support/isolated_execution_state"
require "active_support/notifications"
require "bundler/setup"
require "cli/kit"
require "cli/ui"
require "coverage"
require "diff/lcs"
require "io/console"
require "json"
require "json-schema"
require "minitest"
require "open3"
require "open_router"
require "openai"
require "raix"
require "raix/chat_completion"
require "raix/function_dispatch"
require "roast/helpers/logger"
require "roast/helpers/timeout_handler"
require "ruby-graphviz"
require "shellwords"
require "sqlite3"
require "thor"
require "timeout"
require "tmpdir"
require "zeitwerk"
